CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE article (
    "ArticleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100),
    CONSTRAINT "PK_article" PRIMARY KEY ("ArticleId")
);

CREATE TABLE "Tags" (
    "TagId" character varying(20) NOT NULL,
    "Content" text NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("TagId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241217093058_Init', '9.0.0');

ALTER TABLE article RENAME COLUMN "Title" TO "Name";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241217094722_v1', '9.0.0');

ALTER TABLE article ADD "Content" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241217100017_v2', '9.0.0');

ALTER TABLE "Tags" DROP CONSTRAINT "PK_Tags";

ALTER TABLE "Tags" DROP COLUMN "TagId";

ALTER TABLE "Tags" ADD "TagIdNew" integer GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "Tags" ADD CONSTRAINT "PK_Tags" PRIMARY KEY ("TagIdNew");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241217100951_v3', '9.0.0');

ALTER TABLE "Tags" RENAME COLUMN "TagIdNew" TO "TagId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241217101110_v3-RenameTagId', '9.0.0');

CREATE TABLE "ArticleTags" (
    "ArticleTagId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TagId" integer NOT NULL,
    "ArticleId" integer NOT NULL,
    CONSTRAINT "PK_ArticleTags" PRIMARY KEY ("ArticleTagId"),
    CONSTRAINT "FK_ArticleTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("TagId") ON DELETE CASCADE,
    CONSTRAINT "FK_ArticleTags_article_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES article ("ArticleId") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_ArticleTags_ArticleId_TagId" ON "ArticleTags" ("ArticleId", "TagId");

CREATE INDEX "IX_ArticleTags_TagId" ON "ArticleTags" ("TagId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241217103032_v4', '9.0.0');

COMMIT;

